-- Your SQL goes here
ALTER TABLE rating
    ADD COLUMN create_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE selled_posts (
    id SERIAL PRIMARY KEY,
    product_id 	INTEGER REFERENCES products ON DELETE CASCADE UNIQUE NOT NULL,
    selled_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

