version: '3'
services:
  app_dev:
    image: badconfig/droux:dev
    container_name: rocket-server_dev
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres1_dev:5432/diesel_db
      - RETAIL_CRM_API_KEY=qZPXO3WaF2LLQI3YEZHdpJLoYZxhHdzH
      - SBERBANK_USERNAME=T773007004660-api
      - SBERBANK_PASSWORD=T773007004660
      - SITE_URL=http://178.154.229.126:8080
    volumes:
          - ./Rocket.dev.toml:/droux/Rocket.toml
          - ./static/:/droux/static/
          - ./templates/:/droux/templates/
          #- ./.env.dev:/droux/.env
          - ./migrations:/droux/migrations/
    networks:
      
      - app-network
  nginx_dev:
    image: nginx:1.15-alpine
    container_name: nginx_dev
    restart: unless-stopped
    volumes:
      - ./data/nginx_dev:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - app-network
  postgres_dev:
    image: "postgres:9.6"
    container_name: postgres1_dev
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

