name: Command via SSH UPDATE TEST SERVER master

on: 

    push:
        branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with: 
          command: cd droux-master && sudo git pull && sudo docker build -t badconfig/droux . && docker-compose restart app && docker-compose restart nginx && docker-compose up -d app
          host: ${{ secrets.HOST }}
          username: admin
          privateKey: ${{ secrets.SSH_KEY }}
        env:
          CI: true
